# Generated by Django 3.1 on 2020-09-26 10:34

import datetime
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('list', models.TextField(verbose_name='List')),
                ('style', models.CharField(default=0, max_length=300, null=True, verbose_name='Style')),
                ('remind', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Remind')),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Deadline')),
                ('done', models.BooleanField(default=False, verbose_name='Done')),
                ('draft', models.BooleanField(default=False, verbose_name='Draft')),
                ('date_of_adding', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='DateOfAdding')),
            ],
            options={
                'verbose_name': 'List',
                'verbose_name_plural': 'Lists',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('files', models.FileField(blank=True, upload_to='user_files/', verbose_name='File')),
                ('style', models.CharField(default=0, max_length=300, null=True, verbose_name='Style')),
                ('remind', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Remind')),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Deadline')),
                ('done', models.BooleanField(default=False, verbose_name='Done')),
                ('draft', models.BooleanField(default=False, verbose_name='Draft')),
                ('date_of_adding', models.DateTimeField(default=django.utils.timezone.now, verbose_name='DateOfAdding')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('theme', models.CharField(max_length=100, verbose_name='Theme')),
                ('default_style_note', models.CharField(max_length=300, verbose_name='Style')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('style', models.CharField(max_length=300, verbose_name='Style')),
                ('every_day_remind', models.TimeField(default=0, null=True, verbose_name='EveryDayRemind')),
                ('deadline', models.DateTimeField(default=0, null=True, verbose_name='Deadline')),
                ('done', models.BooleanField(default=False, verbose_name='Done')),
                ('draft', models.BooleanField(default=False, verbose_name='Draft')),
                ('date_of_adding', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='DateOfAdding')),
                ('list', models.ManyToManyField(to='user_page.List', verbose_name='List')),
                ('note', models.ManyToManyField(to='user_page.Note', verbose_name='Note')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_page.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_page.user', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='list',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_page.user', verbose_name='User'),
        ),
    ]
