# Generated by Django 3.1 on 2020-08-30 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='style',
            field=models.CharField(default=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_page.user', verbose_name='User'), max_length=300, verbose_name='Style'),
        ),
    ]
