# Generated by Django 3.1 on 2020-09-09 14:07

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_of_adding',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='DateOfAdding'),
        ),
        migrations.AlterField(
            model_name='note',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='note',
            name='remind',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Remind'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_of_adding',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='DateOfAdding'),
        ),
    ]
