# Generated by Django 3.1 on 2020-09-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='style',
            field=models.CharField(default='white', max_length=300, verbose_name='Style'),
        ),
    ]
