# Generated by Django 3.1 on 2020-08-31 06:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0002_auto_20200830_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='list',
            name='date_of_adding',
            field=models.DateTimeField(default=0, null=True, verbose_name='DateOfAdding'),
        ),
        migrations.AlterField(
            model_name='list',
            name='deadline',
            field=models.DateTimeField(default=0, null=True, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='list',
            name='style',
            field=models.CharField(default=django.db.models.deletion.SET_NULL, max_length=300, null=True, verbose_name='Style'),
        ),
        migrations.AlterField(
            model_name='note',
            name='date_of_adding',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='DateOfAdding'),
        ),
        migrations.AlterField(
            model_name='note',
            name='deadline',
            field=models.DateTimeField(default=0, null=True, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='note',
            name='files',
            field=models.FileField(blank=True, upload_to='user_files/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='note',
            name='style',
            field=models.CharField(default=django.db.models.deletion.SET_NULL, max_length=300, null=True, verbose_name='Style'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_of_adding',
            field=models.DateTimeField(default=0, null=True, verbose_name='DateOfAdding'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(default=0, null=True, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Email'),
        ),
    ]
