# Generated by Django 3.1 on 2020-09-11 05:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0002_auto_20200909_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='list',
            name='remind',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Remind'),
        ),
    ]
