# Generated by Django 3.1 on 2020-09-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0004_auto_20200927_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(default=None, null=True, verbose_name='Deadline'),
        ),
    ]
