# Generated by Django 3.1 on 2020-09-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0005_auto_20200927_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='project',
            name='every_day_remind',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='EveryDayRemind'),
        ),
    ]
