# Generated by Django 3.1 on 2020-09-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0007_auto_20200928_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='list',
            field=models.ManyToManyField(blank=True, null=True, to='user_page.List', verbose_name='List'),
        ),
        migrations.AlterField(
            model_name='project',
            name='note',
            field=models.ManyToManyField(blank=True, null=True, to='user_page.Note', verbose_name='Note'),
        ),
    ]
