# Generated by Django 3.2.4 on 2021-06-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0008_auto_20200928_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='list',
            field=models.ManyToManyField(blank=True, to='user_page.List', verbose_name='List'),
        ),
        migrations.AlterField(
            model_name='project',
            name='note',
            field=models.ManyToManyField(blank=True, to='user_page.Note', verbose_name='Note'),
        ),
    ]
