# Generated by Django 3.2.4 on 2021-06-16 15:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210616_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 16, 15, 7, 32, 753273, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='list',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2021, 6, 16, 15, 7, 32, 755306, tzinfo=utc), verbose_name='date_of_creation_remind'),
        ),
        migrations.AlterField(
            model_name='note',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2021, 6, 16, 15, 7, 32, 755306, tzinfo=utc), verbose_name='date_of_creation_remind'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2021, 6, 16, 15, 7, 32, 755306, tzinfo=utc), verbose_name='date_of_creation_remind'),
        ),
    ]
