# Generated by Django 3.2.4 on 2021-06-17 14:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210617_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 17, 14, 41, 29, 473130, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='list',
            name='date_of_change',
            field=models.DateField(blank=True, null=True, verbose_name='date_of_changing_remind'),
        ),
        migrations.AlterField(
            model_name='list',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2021, 6, 17, 14, 41, 29, 475162, tzinfo=utc), verbose_name='date_of_creation_remind'),
        ),
        migrations.AlterField(
            model_name='note',
            name='date_of_change',
            field=models.DateField(blank=True, null=True, verbose_name='date_of_changing_remind'),
        ),
        migrations.AlterField(
            model_name='note',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2021, 6, 17, 14, 41, 29, 475162, tzinfo=utc), verbose_name='date_of_creation_remind'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_of_change',
            field=models.DateField(blank=True, null=True, verbose_name='date_of_changing_remind'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2021, 6, 17, 14, 41, 29, 475162, tzinfo=utc), verbose_name='date_of_creation_remind'),
        ),
    ]
