# Generated by Django 3.2.4 on 2021-06-21 10:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210621_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='icon',
            field=models.CharField(default='fas fa-file-alt', max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 21, 10, 4, 6, 702317, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='list',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2021, 6, 21, 10, 4, 6, 705315, tzinfo=utc), verbose_name='date_of_creation_remind'),
        ),
        migrations.AlterField(
            model_name='note',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2021, 6, 21, 10, 4, 6, 705315, tzinfo=utc), verbose_name='date_of_creation_remind'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2021, 6, 21, 10, 4, 6, 705315, tzinfo=utc), verbose_name='date_of_creation_remind'),
        ),
    ]
